version: '3'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: batatinha123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    expose: 
      - 5432
  app:
    build: .
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./:/src/
    depends_on:
      - postgres
